services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DOTNET_VERSION: ${DOTNET_VERSION:-10.0}
    env_file:
      - Corelink.Presentation/.env
    environment:
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT:-Development}
    ports:
      - "8080:8080"
